### ISSUE TITLE
n_transExt initialization from big GMP or n_Z values does not work

### ISSUE THREAD

**Issue by fingolfin** [Singular/Singular#1043]
For Singular.jl I've written some more tests, and that uncovered that also n_transExt has issues when initialing this from a big integer. There seems to be truncation if one tries to do that. Consider this Singular.jl example:
```julia
julia> R = FunctionField(QQ, ["a"])[1]
Function Field over Rational Field with transcendence basis n_transExt[(a)]

julia> R(3)^80
147808829414345923316083210206383297601

julia> big(3)^80
147808829414345923316083210206383297601

julia> R(big(3)^80)         # bad result given an mpz_t; via InitMPZ
4389419161382147137

julia> R(n_Z(3)^80))         # bad result given an Singular integer; via SetMap
4389419161382147137
```

I assume this is another case of the above mentioned methods not being implemented?

**Comment by hannes14** [comment]
Am Sun, Jan 17, 2021 at 03:00:42PM -0800 schrieb Max Horn:
> julia> R(big(3)^80)         # bad result given an mpz_t; via InitMPZ
fixed, was not implemented
> 
> julia> R(n_Z(3)^80))         # bad result given an Singular integer; via SetMap
fixed in libSingular, but this is (also) a problem in Singular.jl:
SetMap correctly returned NULL indicating "not implmented/not feasable",
which is not checked for

**Comment by fingolfin** [comment]
Yes, Singular.jl should check for NULL (and I am doing that now), but I also think Singular should support these "obvious" conversions / initializations. Thanks for adding those! I'll work on updating the JLLs and Singular.jl

**Comment by fingolfin** [comment]
The fix here works.

However, initializing an `n_Zp` from an mpz_t seems to be broken: the result is wrong (perhaps always 0?)

**Comment by hannes14** [comment]
fixed with 35c6e2c47bae1f858ec6f4a0cdab911b80a1c383

**Comment by fingolfin** [comment]
@hannes14 something is still wrong here, see https://github.com/oscar-system/libsingular-julia/pull/17

```
julia> R = FunctionField(QQ, ["a", "b", "c"])[1]
Function Field over Rational Field with transcendence basis n_transExt[a, b, c]

julia> R(3)
3

julia> R(big(3))
3

julia> R(big(3)^10)
59049

julia> R(big(3)^80)
[??? unknown Expr ???]
```

**Comment by tthsqe12** [comment]
@fingolfin This indicates that expressify is not working correctly on R(big(3)^80). Will investigate.

**Comment by tthsqe12** [comment]
This is strange and unexpected:
```
julia> Meta.parse("147808829414345923316083210206383297601")
:(147808829414345923316083210206383297601)

julia> ans |> dump
Expr
  head: Symbol macrocall
  args: Array{Any}((3,))
    1: GlobalRef
      mod: Module Core
      name: Symbol @int128_str
    2: Nothing nothing
    3: String "147808829414345923316083210206383297601"
```

**Comment by tthsqe12** [comment]
Just to be clear, this has nothing to do with Singular. The bug is in the julia code.

**Comment by fingolfin** [comment]
Yeah the printing was a read herring. The real issue is https://github.com/oscar-system/Singular.jl/issues/395
