### ISSUE TITLE
(gcc-12) vspace.cc: error: data was not declared in this scope

### ISSUE THREAD

**Issue by orlitzky** [Singular/Singular#1136]
Just forwarding this report along: https://bugs.gentoo.org/841248

gcc-12.1 was released today and I haven't upgraded yet but it seems likely that it's the cause

**Comment by hannes14** [comment]
should be fixed with https://github.com/Singular/Singular/commit/5155427417fa722a27c110b2c1939c0979c6dcbc

**Comment by orlitzky** [comment]
It gets a tiny bit further with https://github.com/Singular/Singular/commit/5155427417fa722a27c110b2c1939c0979c6dcbc, but still fails with gcc-12:

```
libtool: compile:  x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../.. -I../.. -I../.. -I../../libpolys -I../../libpolys -I/var/tmp/portage/sci-mathematics/singular-4.3.0/work/singular-4.3.0 -I/var/tmp/portage/sci-mathematics/singular-4.3.0/work/singular-4.3.0 -I/var/tmp/portage/sci-mathematics/singular-4.3.0/work/singular-4.3.0 -I/var/tmp/portage/sci-mathematics/singular-4.3.0/work/singular-4.3.0/factory -I/var/tmp/portage/sci-mathematics/singular-4.3.0/work/singular-4.3.0/factory/include -O2 -pipe -march=native -O0 -fno-common -c vspace.cc  -fPIC -DPIC -o .libs/vspace.o
vspace.cc: In function 'void vspace::internals::vmem_free(vaddr_t)':
vspace.cc:766:17: error: expected initializer before '-=' token
  766 |   vaddr_t vaddr -= (sizeof(vaddr_t)*2);
      |                 ^~
make[3]: *** [Makefile:766: vspace.lo] Error 1
```

**Comment by orlitzky** [comment]
Better now with https://github.com/Singular/Singular/commit/3ace2096ca279f37180544cc9f2ae746541371dc, thanks!
